# Site wide configuration

title:  Trial & Error
locale: en_US
url:

# Jekyll configuration

permalink: /:categories/:title/
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
fenced_code_blocks: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
safe: true
lsi: false
excerpt_separator: ""
encoding: "utf-8"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  input: GFM

collections:
  tutorials:
    output: true

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      tags: [kit pearson, web development, ruby, ruby on rails, javascript]
  -
    scope:
      path: ""
      type: "tutorials"
    values:
      date: 2013-11-02 00:00:00 -0800
      layout: "tutorials"
      comments: true
      tags: [kit pearson, web development, ruby, ruby on rails, javascript]

# Site owner
owner:
  name: Kit Pearson
  avatar: kiT_120411_1016_Square.jpg
  bio: "Developer of web things. Discovering what I don't know. Ruby and JavaScript for the time being."
  email: dev_kit@icloud.com
  disqus-shortname: trial-and-error
  twitter: kit_pearson
  facebook: #https://www.facebook.com/kiTpearsonPhoto
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kpearson
  stackoverflow: #http://stackoverflow.com/users/1999148/kit
  linkedin: kit-pearson/7/897/222
  instagram: #username
  tumblr: #username
  pinterest: #username
  youtube: #username
  soundcloud: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
